# Tên site
baseURL = "https://trunghieu-it.github.io/TrungHieuIT.github.io-workshop/"
title = "AWS System Manager"
languageCode = "vi"
theme = "hugo-theme-learn"

# Output cho search
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
  themeVariant = "workshop"     # màu chủ đề
  editURL = ""                  # link edit trang
  description = ""
  author = "journeyoftheaverageguy@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

# Ngôn ngữ
[Languages]
[Languages.en]
title = "AWS System Manager"
weight = 1
languageName = "Tiếng Việt"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20
